### ISSUE TITLE
pre-processing the dataset

### ISSUE THREAD

**Issue by znshi** [jcwang123/BA-Transformer#1]
Hi, thanks for your work and  your sharing~

For pre-processing the dataset, when I run python src/point_gen.py, I found there is no main function and no print information~ So, what can I do for the key-patch map generation?

thks~

**Comment by jcwang123** [comment]
Sorry for the confusing. We have re-written the function so that you can not straightly run the file. 
Actually, it provides a function that takes a label path as input and gives an output of the point map.
If you have any questions else, please contact with me !!!

**Comment by znshi** [comment]
Thanks for your reply! Sorry, I have another question, can you share the checkpoint ("/home/wjc/.cache/torch/checkpoints/resnet50-19c8e357.pth") in the resnet.py? Looking forward to your reply~ 

非常感谢~~~

**Comment by jcwang123** [comment]
Please download the weight from this resource:
'''
model_urls = {
    "resnet18": "https://download.pytorch.org/models/resnet18-f37072fd.pth",
    "resnet34": "https://download.pytorch.org/models/resnet34-b627a593.pth",
    "resnet50": "https://download.pytorch.org/models/resnet50-0676ba61.pth",
    "resnet101": "https://download.pytorch.org/models/resnet101-63fe2227.pth",
    "resnet152": "https://download.pytorch.org/models/resnet152-394f9c45.pth",
    "resnext50_32x4d": "https://download.pytorch.org/models/resnext50_32x4d-7cdf4587.pth",
    "resnext101_32x8d": "https://download.pytorch.org/models/resnext101_32x8d-8ba56ff5.pth",
    "wide_resnet50_2": "https://download.pytorch.org/models/wide_resnet50_2-95faca4d.pth",
    "wide_resnet101_2": "https://download.pytorch.org/models/wide_resnet101_2-32ee1156.pth",
}
'''

**Comment by znshi** [comment]
Thank you again for your help!
RuntimeError: stack expects each tensor to be equal size, but got [3, 512, 512] at entry 0 and [2, 512, 512] at entry 3

I am getting the aforementioned error when training on a CASIAV2.0 dataset which is usually used in image forensics, do you konw why?

According to the author's codes, I generate the corresponding Image.npy, Lable.npy and Point.npy files. And I make some changes in dataset/isbi2018.py

`import os
import glob
import json
import torch
import random
import torch.nn as nn
import numpy as np
import torch.utils.data
from torchvision import transforms
import torch.utils.data as data
import torch.nn.functional as F

import albumentations as A


def norm01(x):
    return np.clip(x, 0, 255) / 255


#seperable_indexes = json.load(open('/raid/wl/ISBI_2018/data_split.json', 'r'))


# cross validation
class myDataset(data.Dataset):
    def __init__(self, fold, split, aug=False):
        super(myDataset, self).__init__()
        self.split = split

        # load images, label, point
        self.image_paths = []
        self.label_paths = []
        self.point_paths = []
        self.dist_paths = []

        indexes = [
            l[:-4] for l in os.listdir(
                '/home/datasets/Casiav2/Train/Image'
            )
        ]
        
        temp = 510
        # 9:1
        random.shuffle(indexes)

        train_indexes = indexes[:-temp]
        valid_indexes = indexes[-temp:]
        print('train: {} valid: {}'.format(len(train_indexes),
                                           len(valid_indexes)))
        
        if split == 'train':
            self.image_paths = [
                '/home/datasets/Casiav2/Train/Image/{}.npy'.format(_id)
                for _id in train_indexes
            ]
            self.label_paths = [
                '/home/datasets/Casiav2/Train/Label/{}.npy'.format(_id)
                for _id in train_indexes
            ]
            self.point_paths = [
                '/home/datasets/Casiav2/Train/Point/{}.npy'.format(_id)
                for _id in train_indexes
            ]
        elif split == 'valid':
            self.image_paths = [
                '/home/datasets/Casiav2/Train/Image/{}.npy'.format(_id)
                for _id in valid_indexes
            ]
            self.label_paths = [
                '/home/datasets/Casiav2/Train/Label/{}.npy'.format(_id)
                for _id in valid_indexes
            ]
            self.point_paths = [
                '/home/datasets/Casiav2/Train/Point/{}.npy'.format(_id)
                for _id in valid_indexes
            ]

        print('Loaded {} frames'.format(len(self.image_paths)))
        self.num_samples = len(self.image_paths)
        self.aug = aug

        p = 0.5
        self.transf = A.Compose([
            A.GaussNoise(p=p),
            A.HorizontalFlip(p=p),
            A.VerticalFlip(p=p),
            A.ShiftScaleRotate(p=p),
            #             A.RandomBrightnessContrast(p=p),
        ])

    def __getitem__(self, index):

        image_data = np.load(self.image_paths[index])
        label_data = np.load(self.label_paths[index]) > 0.5
        point_data = np.load(self.point_paths[index]) > 0.5

        if self.aug and self.split == 'train':
            mask = np.concatenate([
                label_data[..., np.newaxis].astype('uint8'),
                point_data[..., np.newaxis]
            ],
                                  axis=-1)
            tsf = self.transf(image=image_data.astype('uint8'), mask=mask)
            image_data, mask_aug = tsf['image'], tsf['mask']
            label_data = mask_aug[:, :, 0]
            point_data = mask_aug[:, :, 1]

        image_data = norm01(image_data)
        label_data = np.expand_dims(label_data, 0)
        point_data = np.expand_dims(point_data, 0)
        image_data = torch.from_numpy(image_data).float()
        label_data = torch.from_numpy(label_data).float()
        point_data = torch.from_numpy(point_data).float()

        image_data = image_data.permute(2, 0, 1)

        return {
            'image_path': self.image_paths[index],
            'label_path': self.label_paths[index],
            'point_path': self.point_paths[index],
            'image': image_data,
            'label': label_data,
            'point': point_data
        }

    def __len__(self):
        return self.num_samples


if __name__ == '__main__':
    from tqdm import tqdm
    dataset = myDataset(fold=0, split='train', aug=False)

    train_loader = torch.utils.data.DataLoader(dataset,
                                               batch_size=8,
                                               shuffle=False,
                                               num_workers=2,
                                               pin_memory=True,
                                               drop_last=True)
    for d in train_loader:
        pass`

**Comment by jcwang123** [comment]
It seems to be the error of array shape.
You could check the each variable's shape during dataset forward pass and then tell me when the error happens.

**Comment by RuosiZhou** [comment]
Hello, I would like to ask how to run point_gen.py, is it convenient to share?
