### ISSUE TITLE
Dataset Question

### ISSUE THREAD

**Issue by leilimaster** [jcwang123/BA-Transformer#10]
Hello,jcWnag, I follow your reademe to train but the following error occured. 
There is no validation data in ISIC2016. I just find the train and test dataset in the website.
How can find the vaild dataset, or have other sulution?
 Thanks for your answer!

 `class myDataset(data.Dataset):
    def __init__(self, split, aug=False):
        super(myDataset, self).__init__()

        self.image_paths = []
        self.label_paths = []
        self.point_paths = []
        self.dist_paths = []

        root_dir = './dataset/isic2016/'
        if split == 'train':
            self.image_paths = glob.glob(root_dir + '/Train/Image/*.npy')
            self.label_paths = glob.glob(root_dir + '/Train/Label/*.npy')
            self.point_paths = glob.glob(root_dir + '/Train/Point/*.npy')
        elif split == 'valid':
            self.image_paths = glob.glob(root_dir + '/Validation/Image/*.npy')
            self.label_paths = glob.glob(root_dir + '/Validation/Label/*.npy')
            self.point_paths = glob.glob(root_dir + '/Validation/Point/*.npy')
        elif split == 'test':
            self.image_paths = glob.glob(root_dir + '/Test/Image/*.npy')
            self.label_paths = glob.glob(root_dir + '/Test/Label/*.npy')
            self.point_paths = glob.glob(root_dir + '/Test/Point/*.npy')
        self.image_paths.sort()
        self.label_paths.sort()
        self.point_paths.sort()

        print('Loaded {} frames'.format(len(self.image_paths)))
        self.num_samples = len(self.image_paths)
        self.aug = aug

        self.transf = A.Compose([
            A.HorizontalFlip(p=0.5),
            A.VerticalFlip(p=0.5),
            A.RandomBrightnessContrast(p=0.2),
            A.Rotate()
        ])`

**Comment by jcwang123** [comment]
We divide the ISIC2016 into two parts for training and validation.
PH2 is always used for the final test.
