### ISSUE TITLE
Is a Binary key-patch map used during training?

### ISSUE THREAD

**Issue by YHYeooooong** [jcwang123/BA-Transformer#11]
Hello, Thanks for sharing good research!

In the paper, figure 2, Binary Key-Patch Map is seem like used in BAG with input image features.
I wonder how it worked in training. So, trying to find the part in the code, but I found this part in train.py. 

https://github.com/jcwang123/BA-Transformer/blob/d1ccdff68beac82d18c2cd64bb800e51d7afc5e1/train.py#L189

It looks like point data(key-patch map or binary key-patch map) is used only for comparison with boundary prediction that came from the model. 
I think I missed the code that uses point data during the trained model. If it is, how the binary key-patch map is used in the training phase?  

Thanks!

**Comment by jcwang123** [comment]
The predicted point maps will be used to:
1) refine the feature (please refer to the network codes);
2) calculate the boundary point loss.

**Comment by YHYeooooong** [comment]
Thank you for the fast comment! 
How about a Binary Key-Patch map made from Ground-Truth Key-Patch Map?
Is it also used in the training phase to feed into the BAG? By the figure2 on the paper, It looks like the binary key-patch map is the input of BAG

**Comment by jcwang123** [comment]
1) The key-patch map is predicted through a full-connection layer and supervised by the GT map.
2) After that, the predicted map is fed into the attention gat for boundary-aware feature enhancement.

**Comment by YHYeooooong** [comment]
So, Summarized what I understand,

The Binary key-patch map(2D shape) in the below pictures is used like a GT map for supervising the predicted key-patch map. 
And, predicted key-patch map is produced from the full-connection layer which gets calculated input image feature as input.

Am I understanding correctly?

![capture_figure2](https://user-images.githubusercontent.com/43724177/185527101-9f185779-af26-4169-9d71-31ee51b69631.png)

**Comment by jcwang123** [comment]
Yes.

**Comment by YHYeooooong** [comment]
Thank you!
I understand clearly
