### ISSUE TITLE
About the parameter in Eq (2).

### ISSUE THREAD

**Issue by LuoXubo** [jcwang123/BA-Transformer#17]
Thanks for your excellent work! After reading your paper, I still don’t understand one thing: 

In Equation 2, $\hat{S_{pred}} = \sigma(d_1^1([d_1^3(Z), d_3^3(Z), d_6^3(Z)]))$, why are the dilation rates set to 1, 3, and 6 in sequence? Is this a conventional setting or a parameter setting obtained through ablation experiments? 

I would appreciate it a lot if you could explain it!

**Comment by jcwang123** [comment]
It is a conventional setting. You could refer to the aspp modules firstly proposed in deeplabv3.
        
            
        
    
                 
            
                font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }Regards,Jiacheng Wang, PhD Student,Department of Computer Science at School of Informatics, Xiamen UniversityXiamen, China, 361005
            
        
             
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/18/2023 12:47
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [jcwang123/BA-Transformer] About the parameter in Eq (2). (Issue #17)
        
      
    
  

Thanks for your excellent work! After reading your paper, I still don’t understand one thing:
In Equation 2, $\hat{S_{pred}} = \sigma(d_1^1([d_1^3(Z), d_3^3(Z), d_6^3(Z)]))$, why are the dilation rates set to 1, 3, and 6 in sequence? Is this a conventional setting or a parameter setting obtained through ablation experiments?
I would appreciate it a lot if you could explain it!

**Comment by LuoXubo** [comment]
Thanks for your reply. I'll close this issue.
