### ISSUE TITLE
the problem of formula (1)

### ISSUE THREAD

**Issue by RuosiZhou** [jcwang123/BA-Transformer#2]
Hello, I recently read your paper, I think it is very good, but I found that formula (1) is missing the residual part of the MSA position, I don’t know if what I put forward is correct, and I hope you can take a look. thanks.

**Comment by jcwang123** [comment]
we simplify the "add" and "LN" operation of MSA and MLP modules in formula (1) but they indeed exist.

**Comment by RuosiZhou** [comment]
OK, thanks very much
