### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/data_split.json'

### ISSUE THREAD

**Issue by tphankr** [jcwang123/BA-Transformer#3]
Thank you for your code,
When I typed python train.py, I face the error as below following, how do we have the data_split.json? Thank you.
![image](https://user-images.githubusercontent.com/37217354/146688005-c1880bd4-9424-4d4e-89d7-a4554e67510e.png)

Thank you @jcwang123.

**Comment by jcwang123** [comment]
please download it from https://drive.google.com/file/d/1mSLt-ipLM9CxrfvwgjJr5V9NKrpnQaQ5.
And put the file into './dataset/'
