### ISSUE TITLE
 TypeError: src data type = 17 is not supported

### ISSUE THREAD

**Issue by a139122679** [jcwang123/BA-Transformer#4]
Traceback (most recent call last):
  File "srcc/process_resize.py", line 87, in <module>
    process_isic2018()
  File "srcc/process_resize.py", line 44, in process_isic2018
    image_new = cv2.resize(image, dim, interpolation=cv2.INTER_CUBIC)
TypeError: src data type = 17 is not supported

**Comment by jcwang123** [comment]
try to convert image into numpy.array

**Comment by a139122679** [comment]
I changed this way, but still will report an error, can you give a detailed change method, I am not familiar with numpy
for image_path, mask_path in zip(image_path_list, mask_path_list):
        if image_path[-3:] == 'jpg':
            print(image_path)
            assert os.path.basename(image_path)[:-4].split(
                '_')[1] == os.path.basename(mask_path)[:-4].split('_')[1]
            _id = os.path.basename(image_path)[:-4].split('_')[1]
            image_path = os.path.join(image_dir_path, image_path)
            mask_path = os.path.join(mask_dir_path, mask_path)
            image = plt.imread(image_path)
            mask = plt.imread(mask_path)

            #image_new = cv2.resize(image, dim, interpolation=cv2.INTER_CUBIC)
            image_new = np.array(image.getdata(), dtype = 'uint8')
            mask_new = cv2.resize(mask, dim, interpolation=cv2.INTER_NEAREST)

**Comment by jcwang123** [comment]
Maybe, you could run this:
        _image = np.array(image).astype('uint8')
        image_new = cv2.resize(_image, dim, interpolation=cv2.INTER_CUBIC)

tell me whether it works, or what error happens.

**Comment by a139122679** [comment]
Hello, your method I tried, can run correctly and process the data, thank you for the excellent work
