### ISSUE TITLE
the question of M^pred

### ISSUE THREAD

**Issue by RuosiZhou** [jcwang123/BA-Transformer#5]
Hello, I have a question, the output of the key-patch map generator not is a binary image？It is a probability image generated by sgimoid？

**Comment by jcwang123** [comment]
Firstly, we generate a set of key point, saving their coordinates.
Secondly, we transfer the coordinates into heatmap with gauss filter.
Thirdly, during training, the key-path map is used as a binary image (heatmap > 0).
-------
At the final step, you could alternatively try to use the heatmap for training.
