### ISSUE TITLE
Questions about model pre-training

### ISSUE THREAD

**Issue by printorange** [jcwang123/BA-Transformer#6]
Hello, author, I noticed that you mentioned in the article that all network encoders have been pre-trained on ImageNet, may I ask whether the encoders you mentioned refer to ResNet50 or ResNet50 + Transformer's encoder?

Also, as I understand it, in the BAT class there is a decoder section in Transformer regardless of which Transformer is used, so what is use_decoder for (although it seems you set it to False).

Thank you for the response

**Comment by jcwang123** [comment]
Q1. Only ResNet-50 has been pre-trained.
Q2. In the miccai version, we used the decoder as an extensive attention gate and you can set it to True.
